config/routes.rb
Rails.application.routes.draw do
  get 'pages/root'
  devise_for :hosts, skip: [:registrations], controllers: { sessions: "hosts/sessions", registrations: "hosts/registrations" }
  as :host do
    get 'hosts/edit' => 'devise/registrations#edit', :as => 'edit_host_registration'
    put '/hosts' => 'hosts/registrations#update', :as => 'host_registration'
    get '/hosts' => 'devise/registrations#edit' # Avoid errors if refresh page after editing fail
  end
  namespace :user do
    post 'voting/vote'
  end
  namespace :user do
  end
  resources :profile_photos, only: [:create]
  devise_for :users, controllers: { sessions: "users/sessions" }
  get 'user/events/current', to: 'user/events/current#attendees'

  get 'user/profile' => 'user/profile#profile', as: :user_profile
  get 'user/profile/settings' => 'user/profile#settings', as: :user_profile_settings
  get 'user/profile/messages' => 'user/profile#messages', as: :user_profile_messages

  resources :users, :controller=>:users, except: [:new, :create, :index]

  # These don't seem to like namespacing much
  get 'user/events/info/:id/attendees' => 'user/events/current#attendees', as: :attendees_user_current_event
  get 'user/events/info/:id/favorites' => 'user/events/current#favorites', as: :favorites_user_current_event
  get 'user/events/info/:id/inbox' => 'user/events/current#inbox', as: :inbox_user_current_event
  get 'user/events/info/:id' => 'user/events/current#attendees', as: :user_current_event
  post 'user/events/info/:id/message' => 'user/events/current#message_modal', as: :user_current_message_modal


  get 'user/events' => 'user/events#index'
  get 'user', to: 'user/events#index'

  namespace :user do
    resources :events, only: [:show, :index] do
      collection do
        get 'my_events'
        get 'join'
        post 'join'
        post 'modal'
        get 'search'
      end
    end

    resources :private_messages
  end

  get 'admin', to: 'admin/events#index'
  namespace :admin do
    resources :events, :places
  end

  root "pages#root"
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/event.rb
class Event < ApplicationRecord
  after_initialize :set_default_values
  before_validation :set_code, unless: Proc.new { |event| event.code.present? }
  before_save :split_start_end_at

  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users

  belongs_to :host
  belongs_to :place

  validates :host, presence: true, on: :create
  validates :name, :address, :description, presence: true
  validates :code, presence: true, uniqueness: true
  validates :start_end_at, :place_id, presence: true
  validates :description, length: { minimum: 2, maximum: 500 }
  validates :ticket_purchase_url, url: { allow_blank: true }
  validates :contact_info, length: { minimum: 10, maximum: 250, :allow_blank => true }
  validates :display_profiles_after_minutes,
            :display_profiles_for_minutes,
            :allow_messaging_after_minutes,
            :allow_messaging_for_minutes,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0,
            }

  CODE_CHARACTERS = "2456789BCDFGHJKLMNPRSTVWXZ".split("").freeze

  EVENT_STATUS_INACTIVE = "Inactive".freeze
  EVENT_STATUS_ACTIVE = "Active".freeze
  EVENT_STATUSES = [EVENT_STATUS_INACTIVE, EVENT_STATUS_ACTIVE].freeze
  validates :event_status, :inclusion => { :in => Event::EVENT_STATUSES }

  EVENT_TYPE_SPEED_DATING = "Speed Dating".freeze
  EVENT_TYPE_MIXER = "Mixer".freeze
  EVENT_TYPE_NETWORKING = "Networking".freeze
  EVENT_TYPE_OTHER = "Other".freeze
  EVENT_TYPES = [EVENT_TYPE_SPEED_DATING, EVENT_TYPE_MIXER, EVENT_TYPE_NETWORKING, EVENT_TYPE_OTHER].freeze
  validates :event_type, :inclusion => { :in => Event::EVENT_TYPES }

  scope :active, -> { where(event_status: EVENT_STATUS_ACTIVE) }
  scope :inactive, -> { where(event_status: EVENT_STATUS_INACTIVE) }

  def active?
    event_status == EVENT_STATUS_ACTIVE
  end

  def self.past
    active.where(end_at: Time.at(0)..Time.current)
  end

  def self.current
    active.
    where(
      start_at: Time.at(0)..Time.current,
      end_at: Time.current..DateTime::Infinity.new,
    )
  end

  def self.upcoming
    active.where(start_at: Time.current..DateTime::Infinity.new)
  end

  def tense
    if Event.past.include?(self)
      "Past"
    elsif Event.current.include?(self)
      "Current"
    elsif Event.upcoming.include?(self)
      "Upcoming"
    else
      "Pending"
    end
  end

  def self.find_by_code(entered_code)
    find_by(code: entered_code)
  end

  def set_default_values
    # Defaults are not intended to be valid, only sensible.
    # With defaults Model.create should always fail.
    self.name ||= ""
    self.description ||= ""
    self.code ||= ""
    self.event_status ||= ""
    self.event_type ||= ""
    self.display_profiles_after_minutes ||=  30 # Temp
    self.display_profiles_for_minutes   ||= 300 # Temp
    self.allow_messaging_after_minutes  ||=  30 # Temp
    self.allow_messaging_for_minutes    ||= 300 # Temp
  end

  def standardize
  end

  def split_start_end_at
    # Expected format of start_end_at: 08/18/2018 3:56 PM - 08/18/2018 3:56 PM
    self.start_at, self.end_at = self
    .start_end_at
    .split(" - ")
    .map do |date|
      datetime = DateTime.strptime("#{date} #{place.timezone}", "%m/%d/%Y %H:%M %p %z").to_time
      datetime_formatted = datetime.strftime("%Y-%m-%d %H:%M %p")
      ActiveSupport::TimeZone[place.timezone].parse(datetime_formatted)
    end
  end

  def set_code
    # Use devise for
    self.code = generate_code
  end

  def self.code_digits_required(num_events = 0)
    # Require enough digits to ensure very low probability of collision
    if num_events == 0
      num_events = Event.all.size
    end
    required_solution_space = 2 * num_events + 1

    required = Math.log(required_solution_space,CODE_CHARACTERS.size).ceil + 3
    required
  end

  def generate_code
    existing_codes = Event.all.pluck(:code)

    no_code = nil

    10.times do
      new_code = Event.code_digits_required.times.map { CODE_CHARACTERS.sample  }.join("")

      return new_code unless existing_codes.include?(new_code)
    end

    puts "NO unique code could be generated"

    no_code
  end

  def display_profiles_starts_at
    start_at + display_profiles_after_minutes.minutes
  end

  def display_profiles_ends_at
    display_profiles_starts_at + display_profiles_for_minutes.minutes
  end

  def display_profiles?
    display_profiles_starts_at <= Time.current && Time.current <= display_profiles_ends_at
  end

  def allow_messaging_starts_at
    end_at + allow_messaging_after_minutes.minutes
  end

  def allow_messaging_ends_at
    allow_messaging_starts_at + allow_messaging_for_minutes.minutes
  end

  def allow_messaging?
    allow_messaging_starts_at <= Time.current && Time.current <= allow_messaging_ends_at
  end

  def allow_messaging_status_message
    if Time.current < allow_messaging_starts_at
      "Messaging will be allowed #{allow_messaging_starts_at_zoned_datetime}"
    elsif Time.current > allow_messaging_ends_at
      "Messaging expired #{allow_messaging_ends_at_zoned_datetime}"
    else
      "Messaging is allowed"
    end
  end

  def current_time
    Time.current
  end


  zoned_methods = [
    :start_at, :end_at,
    :display_profiles_starts_at, :display_profiles_ends_at,
    :allow_messaging_starts_at, :allow_messaging_ends_at,
    # temp Methods
    :current_time
  ]
  zoned_methods.each do |zone_method|
    # Defines the following instance helper methods
    #   start_at_zoned, start_at_zoned_date, start_at_zoned_time, start_at_zoned_datetime
    #   end_at_zoned, end_at_zoned_date, end_at_zoned_time, end_at_zoned_datetime
    #   display_profiles_starts_at_zoned, display_profiles_starts_at_zoned_date,
    #     display_profiles_starts_at_zoned_time, display_profiles_starts_at_zoned_datetime
    #   display_profiles_ends_at_zoned, display_profiles_ends_at_zoned_date,
    #     display_profiles_ends_at_zoned_time, display_profiles_ends_at_zoned_datetime
    #   allow_messaging_starts_at_zone, allow_messaging_starts_at_zoned_date,
    #     allow_messaging_starts_at_zoned_time, allow_messaging_starts_at_zoned_datetime
    #   allow_messaging_ends_at_zoned, allow_messaging_ends_at_zoned_date,
    #     allow_messaging_ends_at_zoned_time, allow_messaging_ends_at_zoned_datetime
    # Note: Refactor this to 4 view helper methods if more methods are added

    define_method("#{zone_method}_zoned") do
      send(zone_method).in_time_zone(place.timezone)
    end

    define_method("#{zone_method}_zoned_date") do
      send(zone_method).in_time_zone(place.timezone).strftime("#{place.date_format}")
    end

    define_method("#{zone_method}_zoned_time") do
      send(zone_method).in_time_zone(place.timezone).strftime("#{place.time_format}")
    end

    define_method("#{zone_method}_zoned_datetime") do
      send(zone_method).in_time_zone(place.timezone).strftime("#{place.date_format} #{place.time_format}")
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :redirect_unless_event_host, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if current_host.admin?
      @events = Event.all
    else
      @events = Event.where(host_id: current_host.id)
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    puts event_params.inspect
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  protected

    def redirect_unless_event_host
      if !(current_user == @event.host? ||  current_user.admin?)
        redirect_to admin_events_path
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(
        :place_id, :host_id,
        :start_end_at, :name, :address, :description, :code, :event_status, :event_type,
        :ticket_purchase_url, :contact_info,
        :display_profiles_after_minutes, :display_profiles_for_minutes,
        :allow_messaging_after_minutes, :allow_messaging_for_minutes
      )
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    puts event_params.inspect
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(
        :place_id,
        :start_end_at, :name, :address, :description, :code, :event_status, :event_type,
        :display_profiles_after_minutes, :display_profiles_for_minutes,
        :allow_messaging_after_minutes, :allow_messaging_for_minutes
      )
    end
end

app/controllers/user/events/current_controller.rb
class User::Events::CurrentController < UserController
  before_action :redirect_unless_current_event

  def attendees
    @event_users = @current_event.event_users
  end

  def favorites
    @favorite_ids = current_user
    .votes # Favorites/blocks
    .up # Favorites
    .for_type(User) # Users only
    .pluck(:votable_id) # Get list of user ids

    @event_users = EventUser.where(event_id: @current_event.id, user_id: @favorite_ids)
  end

  def inbox
    # @messages = User::PrivateMessage
    # .where(recipient_id: current_user.id, event_id: @current_event.id)
    # .where.not(sender_id: current_user.blocked_user_ids)
    # .or(
    #   User::PrivateMessage
    #   .where(sender_id: current_user.id, event_id: @current_event.id)
    #   .where.not(sender_id: current_user.blocked_user_ids)
    # ).includes(:sender, :event, event: :place)

    @messages = User::PrivateMessage.threads_for(current_user, @current_event.id)
  end

  def message_modal
    @send_to = User.find(params[:send_to_id])

    respond_to do |format|
      format.js
    end
  end

  private

    def redirect_unless_current_event
      if @current_event.nil?
        redirect_to root_path
      end
    end
end

app/controllers/user/events_controller.rb
class User::EventsController < UserController
  before_action :redirect_unless_active_event, only: [:show, :modal]
  before_action :set_event, only: [:show, :modal]

  def index
    redirect_to my_events_user_events_path
  end

  def show
  end

  def my_events
    @events = current_user.events.reorder(start_at: :desc)
  end

  def join
    @event = Event.find_by_code(params[:code])
    if @event.present? && current_user.present?
      EventUser.create(event_id: @event.id, user_id: current_user.id)
      flash[:success] = "You have joined this event"
      redirect_to my_events_user_events_path
    end
  end

  def search
    @events = Event.active.upcoming
  end

  def modal
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def redirect_unless_active_event
      redirect_to my_events_user_events_path unless @event.active?
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user/events/current_helper.rb
module User::Events::CurrentHelper
end

app/views/admin/events/_form.html.erb
<%= form_for [:admin, @event], :html => { :class => "form-horizontal event" } do |f| %>
  <%= f.hidden_field :host_id, value: @event.host_id || current_host.id %>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :start_end_at, "Event Runs", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :start_end_at, :class => 'form-control calentim col-lg-10' %>
    </div>
    <%=f.error_span(:start_end_at) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :place_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :place_id, Place.pluck(:name, :id), {}, { :class => 'form-control' } %>
    </div>
    <%=f.error_span(:place_id) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :event_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :event_type, Event::EVENT_TYPES, {}, { :class => 'form-control' } %>
    </div>
    <%=f.error_span(:event_type) %>
  </div>
  <div class="form-group">
    <%= f.label :event_status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :event_status, Event::EVENT_STATUSES, {}, { :class => 'form-control' } %>
    </div>
    <%=f.error_span(:event_status) %>
  </div>
  <div class="form-group">
    <%= f.label :ticket_purchase_url, "Ticket Purchase URL", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ticket_purchase_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ticket_purchase_url) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_info, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :contact_info, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_info) %>
  </div>
  <div class="form-group">
    <%= f.label :display_profiles_after_minutes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :display_profiles_after_minutes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:display_profiles_after_minutes) %>
  </div>
  <div class="form-group">
    <%= f.label :display_profiles_for_minutes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :display_profiles_for_minutes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:display_profiles_for_minutes) %>
  </div>
  <div class="form-group">
    <%= f.label :allow_messaging_after_minutes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :allow_messaging_after_minutes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:allow_messaging_after_minutes) %>
  </div>
  <div class="form-group">
    <%= f.label :allow_messaging_for_minutes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :allow_messaging_for_minutes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:allow_messaging_for_minutes) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_events_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script>
  var calentimOptions = {
    minDate: moment("<%= Time.current.yesterday.to_date %>", "YYYY-MM-DD"),
    showHeader: false, // Hide selected dates
    showFooter: false, // Hide ranges
  };

  $(".calentim").calentim(calentimOptions);
</script>

app/views/admin/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%="All" if current_host.admin? %> <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:start_at) %></th>
      <th><%= model_class.human_attribute_name(:end_at) %></th>
      <th><%= model_class.human_attribute_name(:event_status) %></th>
      <th><%= model_class.human_attribute_name(:event_type) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, admin_event_path(event) %></td>
        <td><%= event.name %></td>
        <td><%= event.start_at_zoned_date %><br><%= event.start_at_zoned_time %></td>
        <td><%= event.end_at_zoned_date %><br><%= event.end_at_zoned_time %></td>
        <td><%= event.event_status %></td>
        <td><%= event.event_type %></td>
        <td><%= event.code %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admin_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_event_path,
            :class => 'btn btn-primary' %>

app/views/admin/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:start_at) %>:</strong></dt>
  <dd><%= @event.start_at_zoned_datetime %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_at) %>:</strong></dt>
  <dd><%= @event.end_at_zoned_datetime %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @event.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>
  <dd><%= @event.place.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @event.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_status) %>:</strong></dt>
  <dd><%= @event.event_status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_type) %>:</strong></dt>
  <dd><%= @event.event_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ticket_purchase_url) %>:</strong></dt>
  <dd>
    <% if @event.ticket_purchase_url.present? %>
      <%= link_to @event.ticket_purchase_url, @event.ticket_purchase_url, target: "_blank" %>
    <% else %>
      Not Provided
    <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_info) %>:</strong></dt>
  <dd>
    <% if @event.contact_info.present? %>
      <%= simple_format @event.contact_info %>
    <% else %>
      Not Provided
    <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:display_profiles_after_minutes) %>:</strong></dt>
  <dd><%= @event.display_profiles_after_minutes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:display_profiles_for_minutes) %>:</strong></dt>
  <dd><%= @event.display_profiles_for_minutes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:allow_messaging_after_minutes) %>:</strong></dt>
  <dd><%= @event.allow_messaging_after_minutes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:allow_messaging_for_minutes) %>:</strong></dt>
  <dd><%= @event.allow_messaging_for_minutes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_at) %>:</strong></dt>
  <dd><%= @event.start_at_zoned_datetime %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_at) %>:</strong></dt>
  <dd><%= @event.end_at_zoned_datetime %></dd>
  <dt><strong>Display Profile starts:</strong></dt>
  <dd><%= @event.display_profiles_after_minutes %></dd>
  <dt><strong>Display Profile ends:</strong></dt>
  <dd><%= @event.display_profiles_for_minutes %></dd>
  <dt><strong>Messaging Starts:</strong></dt>
  <dd><%= @event.allow_messaging_starts_at_zoned_datetime %></dd>
  <dt><strong>Messaging ends:</strong></dt>
  <dd><%= @event.allow_messaging_ends_at_zoned_datetime %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_events_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_event_path(@event), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>