config/routes.rb
Rails.application.routes.draw do
  get 'pages/root'
  devise_for :hosts, skip: [:registrations], controllers: { sessions: "hosts/sessions", registrations: "hosts/registrations" }
  as :host do
    get 'hosts/edit' => 'devise/registrations#edit', :as => 'edit_host_registration'
    put '/hosts' => 'hosts/registrations#update', :as => 'host_registration'
    get '/hosts' => 'devise/registrations#edit' # Avoid errors if refresh page after editing fail
  end
  namespace :user do
    post 'voting/vote'
  end
  namespace :user do
  end
  resources :profile_photos, only: [:create]
  devise_for :users, controllers: { sessions: "users/sessions" }
  get 'user/events/current', to: 'user/events/current#attendees'

  get 'user/profile' => 'user/profile#profile', as: :user_profile
  get 'user/profile/settings' => 'user/profile#settings', as: :user_profile_settings
  get 'user/profile/messages' => 'user/profile#messages', as: :user_profile_messages

  resources :users, :controller=>:users, except: [:new, :create, :index]

  # These don't seem to like namespacing much
  get 'user/events/info/:id/attendees' => 'user/events/current#attendees', as: :attendees_user_current_event
  get 'user/events/info/:id/favorites' => 'user/events/current#favorites', as: :favorites_user_current_event
  get 'user/events/info/:id/inbox' => 'user/events/current#inbox', as: :inbox_user_current_event
  get 'user/events/info/:id' => 'user/events/current#attendees', as: :user_current_event
  post 'user/events/info/:id/message' => 'user/events/current#message_modal', as: :user_current_message_modal


  get 'user/events' => 'user/events#index'
  get 'user', to: 'user/events#index'

  namespace :user do
    resources :events, only: [:show, :index] do
      collection do
        get 'my_events'
        get 'join'
        post 'join'
        post 'modal'
        get 'search'
      end
    end

    resources :private_messages
  end

  get 'admin', to: 'admin/events#index'
  namespace :admin do
    resources :events, :places
  end

  root "pages#root"
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/place.rb
class Place < ApplicationRecord
  has_one :event, dependent: :destroy

  validates :tax_rate, :timezone, :currency, :time_format, :date_format, presence: true
  validates :tax_rate,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than: 1,
            }

  TIMEZONES = [
    "Pacific Time (US & Canada)",
    "Mountain Time (US & Canada)",
    "Central Time (US & Canada)",
    "Eastern Time (US & Canada)",
    "Atlantic Time (Canada)"
  ]
  validates :timezone, :inclusion => { :in => Place::TIMEZONES }

  CURRENCIES = [
    "USD",
    "CAN"
  ]
  validates :currency, :inclusion => { :in => Place::CURRENCIES }
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < AdminController
  before_action :authenticate_admin!

  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to [:admin, @place], notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to [:admin, @place], notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(
        :name, :timezone, :tax_rate, :currency
      )
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(
        :name, :timezone, :tax_rate, :currency
      )
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/places/_form.html.erb
<%= form_for [:admin, @place], :html => { :class => "form-horizontal event" } do |f| %>

  <% if @place.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@place.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :timezone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :timezone, Place::TIMEZONES, :class => 'form-control' %>
    </div>
    <%=f.error_span(:timezone) %>
  </div>
  <div class="form-group">
    <%= f.label :tax_rate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tax_rate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tax_rate) %>
  </div>
  <div class="form-group">
    <%= f.label :currency, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :currency, Place::CURRENCIES, :class => 'form-control' %>
    </div>
    <%=f.error_span(:currency) %>
  </div>
  <div class="form-group">
    <%= f.label :date_format, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :date_format, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date_format) %>
  </div>
  <div class="form-group">
    <%= f.label :time_format, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :time_format, :class => 'form-control' %>
    </div>
    <%=f.error_span(:time_format) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_places_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/places/edit.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/places/index.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:timezone) %></th>
      <th><%= model_class.human_attribute_name(:tax_rate) %></th>
      <th><%= model_class.human_attribute_name(:currency) %></th>
      <th><%= model_class.human_attribute_name(:date_format) %></th>
      <th><%= model_class.human_attribute_name(:time_format) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.id, admin_place_path(place) %></td>
        <td><%= place.name %></td>
        <td><%= place.timezone %></td>
        <td><%= place.tax_rate %></td>
        <td><%= place.currency %></td>
        <td><%= Time.current.in_time_zone(place.timezone).strftime(place.date_format) %><br><%= place.date_format %></td>
        <td><%= Time.current.in_time_zone(place.timezone).strftime(place.time_format) %><br><%= place.time_format %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admin_place_path(place), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_place_path(place), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_place_path(place),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_place_path,
            :class => 'btn btn-primary' %>

app/views/admin/places/new.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/places/show.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @place.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:timezone) %>:</strong></dt>
  <dd><%= @place.timezone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tax_rate) %>:</strong></dt>
  <dd><%= @place.tax_rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:currency) %>:</strong></dt>
  <dd><%= @place.currency %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_format) %>:</strong></dt>
  <dd><%= @place.date_format %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time_format) %>:</strong></dt>
  <dd><%= @place.time_format %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_places_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_place_path(@place), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_place_path(@place),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>