config/routes.rb
Rails.application.routes.draw do
  get 'pages/root'
  devise_for :hosts, skip: [:registrations], controllers: { sessions: "hosts/sessions", registrations: "hosts/registrations" }
  as :host do
    get 'hosts/edit' => 'devise/registrations#edit', :as => 'edit_host_registration'
    put '/hosts' => 'hosts/registrations#update', :as => 'host_registration'
    get '/hosts' => 'devise/registrations#edit' # Avoid errors if refresh page after editing fail
  end
  namespace :user do
    post 'voting/vote'
  end
  namespace :user do
  end
  resources :profile_photos, only: [:create]
  devise_for :users, controllers: { sessions: "users/sessions" }
  get 'user/events/current', to: 'user/events/current#attendees'

  get 'user/profile' => 'user/profile#profile', as: :user_profile
  get 'user/profile/settings' => 'user/profile#settings', as: :user_profile_settings
  get 'user/profile/messages' => 'user/profile#messages', as: :user_profile_messages

  resources :users, :controller=>:users, except: [:new, :create, :index]

  # These don't seem to like namespacing much
  get 'user/events/info/:id/attendees' => 'user/events/current#attendees', as: :attendees_user_current_event
  get 'user/events/info/:id/favorites' => 'user/events/current#favorites', as: :favorites_user_current_event
  get 'user/events/info/:id/inbox' => 'user/events/current#inbox', as: :inbox_user_current_event
  get 'user/events/info/:id' => 'user/events/current#attendees', as: :user_current_event
  post 'user/events/info/:id/message' => 'user/events/current#message_modal', as: :user_current_message_modal


  get 'user/events' => 'user/events#index'
  get 'user', to: 'user/events#index'

  namespace :user do
    resources :events, only: [:show, :index] do
      collection do
        get 'my_events'
        get 'join'
        post 'join'
        post 'modal'
        get 'search'
      end
    end

    resources :private_messages
  end

  get 'admin', to: 'admin/events#index'
  namespace :admin do
    resources :events, :places
  end

  root "pages#root"
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_voter
  acts_as_votable # Can block/favorite this

  has_uploadcare_file :photo

  has_many :profile_photos
  has_many :event_users, dependent: :destroy
  has_many :events, through: :event_users

  INTERESTS = [
    INTERESTS_SOCIAL = "Social".freeze,
    INTERESTS_PROFESSIONAL = "Professional".freeze,
    INTERESTS_ROMANCE = "Romance".freeze,
  ].freeze
  validate :interests_allowed
  serialize :interests

  validates :email, :first_name, :last_name, :birthdate, :gender, :photo, presence: true

  validates :bio, length: { maximum: 150 }

  before_validation :standardize

  GENDER_MALE = "Male"
  GENDER_FEMALE = "Female"
  GENDERS = [GENDER_MALE, GENDER_FEMALE]
  validates :gender, :inclusion => { :in => User::GENDERS }

  after_save :find_create_profile_photo # update profile photo user_id

  VOTE_STATUS_FAVORITE = "Favorite"
  VOTE_STATUS_NONE = "None"
  VOTE_STATUS_BLOCK = "Block"


  def interests_allowed
    puts interests.inspect
    if interests.present? && (interests.split(',') - INTERESTS).size > 0
      errors.add(:interests, "is not valid")
    end
  end

  def standardize
    #self.birthdate = DateTime.strptime(birthdate, "%m/%d/%Y %H:%M %p")
  end

  def find_create_profile_photo
    if photo.present?
      profile_picture = ProfilePhoto.find_or_create_by(url: self.photo.to_s)
      if !profile_picture.user_id.present?
        profile_picture.update(user_id: id) if id.present?
      end
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def age
    # Source: https://medium.com/@craigsheen/calculating-age-in-rails-9bb661f11303
    # May be slightly off based on timezone
    ((Time.current - birthdate.to_time) / 1.year.seconds).floor
  end

  def vote_status(other_user)
    vote = self.voted_as_when_voted_for(other_user)
    case vote
    when true
      User::VOTE_STATUS_FAVORITE
    when nil
      User::VOTE_STATUS_NONE
    when false
      User::VOTE_STATUS_BLOCK
    end
  end

  def has_blocked?(other_user)
    vote_status(other_user) == User::VOTE_STATUS_BLOCK
  end

  def has_favorited?(other_user)
    vote_status(other_user) == User::VOTE_STATUS_FAVORITE
  end

  def blocked_user_ids
    @blocked_users = self
    .votes # Favorites/blocks
    .down # Blocked
    .for_type(User) # Users only
    .pluck(:votable_id) # Get list of votable ids
  end

  def blocked_users
    @blocked_users = self
    .votes # Favorites/blocks
    .down # Blocked
    .for_type(User) # Users only
    .votables # Get list of votables
  end

end

app/controllers/user/events/current_controller.rb
class User::Events::CurrentController < UserController
  before_action :redirect_unless_current_event

  def attendees
    @event_users = @current_event.event_users
  end

  def favorites
    @favorite_ids = current_user
    .votes # Favorites/blocks
    .up # Favorites
    .for_type(User) # Users only
    .pluck(:votable_id) # Get list of user ids

    @event_users = EventUser.where(event_id: @current_event.id, user_id: @favorite_ids)
  end

  def inbox
    # @messages = User::PrivateMessage
    # .where(recipient_id: current_user.id, event_id: @current_event.id)
    # .where.not(sender_id: current_user.blocked_user_ids)
    # .or(
    #   User::PrivateMessage
    #   .where(sender_id: current_user.id, event_id: @current_event.id)
    #   .where.not(sender_id: current_user.blocked_user_ids)
    # ).includes(:sender, :event, event: :place)

    @messages = User::PrivateMessage.threads_for(current_user, @current_event.id)
  end

  def message_modal
    @send_to = User.find(params[:send_to_id])

    respond_to do |format|
      format.js
    end
  end

  private

    def redirect_unless_current_event
      if @current_event.nil?
        redirect_to root_path
      end
    end
end

app/controllers/user/events_controller.rb
class User::EventsController < UserController
  before_action :redirect_unless_active_event, only: [:show, :modal]
  before_action :set_event, only: [:show, :modal]

  def index
    redirect_to my_events_user_events_path
  end

  def show
  end

  def my_events
    @events = current_user.events.reorder(start_at: :desc)
  end

  def join
    @event = Event.find_by_code(params[:code])
    if @event.present? && current_user.present?
      EventUser.create(event_id: @event.id, user_id: current_user.id)
      flash[:success] = "You have joined this event"
      redirect_to my_events_user_events_path
    end
  end

  def search
    @events = Event.active.upcoming
  end

  def modal
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def redirect_unless_active_event
      redirect_to my_events_user_events_path unless @event.active?
    end

end

app/controllers/user/private_messages_controller.rb
class User::PrivateMessagesController < UserController
  before_action :set_user_private_message, only: [:show, :edit, :update, :destroy]
  after_action :mark_messages_as_read, only: [:index]

  def index
    @sender = User.find_by(id: params[:sender_id])
    @event = Event.find_by(id: params[:event_id])

    @user_private_messages = User::PrivateMessage
    .messages_for(current_user.id, params[:sender_id], params[:event_id]).reorder(created_at: :asc)
  end

  # POST /user/private_messages
  # POST /user/private_messages.json
  def create
    @user_private_message = User::PrivateMessage.new(user_private_message_params)

    # Reject messages not allowed to be sent.
    # Can only send messages when event allows it.
    # Can only send messages if they are attending that event
    # Blocked users are allowed to send messages to those who blocked them, but the recipient will not see them.

    respond_to do |format|
      if @user_private_message.event.allow_messaging?
        sender = @user_private_message.sender
        recipient = @user_private_message.recipient
        if (sender.events.ids & recipient.events.ids).include?(@user_private_message.event.id)
          if @user_private_message.save
            format.html { redirect_to inbox_user_current_event_path(id: @user_private_message.event_id), notice: 'Private message was successfully created.' }
            format.json { render :show, status: :created, location: @user_private_message }
          else
            format.html { render :new }
            format.json { render json: @user_private_message.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to root_path, notice: "This message is not valid" }
          format.json { render json: {error: "This message is not valid"}, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to root_path, notice: "Messaging is not currently allowed for this event" }
        format.json { render json: {error: "Messaging is not currently allowed for this event"}, status: :unauthorized }
      end

    end
  end

  # PATCH/PUT /user/private_messages/1
  # PATCH/PUT /user/private_messages/1.json
  def update
    respond_to do |format|
      if @user_private_message.update(user_private_message_params)
        format.html { redirect_to @user_private_message, notice: 'Private message was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_private_message }
      else
        format.html { render :edit }
        format.json { render json: @user_private_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/private_messages/1
  # DELETE /user/private_messages/1.json
  def destroy
    # @user_private_message.destroy
    # respond_to do |format|
    #   format.html { redirect_to user_private_messages_url, notice: 'Private message was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_private_message
      @user_private_message = User::PrivateMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_private_message_params
      pm_hash = params.require(:user_private_message).permit(
        :content, :sender_id, :recipient_id, :event_id, message_intent: [])
      pm_hash[:message_intent] = pm_hash[:message_intent].to_a.select { |mi| mi.present? }.join(',')
      if pm_hash[:message_intent].blank?
        pm_hash[:message_intent] = User::PrivateMessage.where(
          sender_id: pm_hash[:sender_id],
          recipient_id: pm_hash[:recipient_id],
        ).first&.message_intent
      end

      pm_hash
    end

    def mark_messages_as_read
      User::PrivateMessage
      .unread_messages_for(current_user.id, params[:event_id], params[:sender_id])
      .update_all(message_read: true)
    end
end

app/controllers/user/profile_controller.rb
class User::ProfileController < UserController
  def profile
    @user = current_user
  end

  def settings
  end

  def messages
    @messages = User::PrivateMessage.threads_for(current_user.id)
  end
end

app/controllers/user/voting_controller.rb
class User::VotingController < ApplicationController
  def vote
    @voter = User.find(params[:voter_id])
    @votable = User.find(params[:votable_id])
    @vote_action = params[:vote_action].to_s.downcase.to_sym
    @action_scope = params[:action_scope].to_s.downcase.to_sym

    case @vote_action
    when :upvote
      puts "Upvote"
      @voter.upvotes(@votable)
    when :downvote
      puts "downvote"
      @voter.downvotes(@votable)
    when :unvote
      puts "unvotes"

      @voter.votes.where(votable_id: @votable.id).destroy_all
    end

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  # All user controllers should inherit from this controller

  layout "user"

   # Refactor to handle admin/host/user authentication
   # => https://github.com/plataformatec/devise/wiki/How-to-Setup-Multiple-Devise-User-Models
   #    => May need to add sessions/registrations controllers
  before_action :authenticate_user!

  before_action :set_current_event

  def set_current_event
    @current_event = Event.find_by(id: params[:id].to_i) || current_user.events.current.reorder(:start_at).first
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to user_profile_path
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_profile_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render 'user/profile/profile' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      user_params_hash = params.require(:user).permit(
        :email, :first_name, :last_name, :birthdate, :gender,
        :career, :school, :location, :bio,
        :photo,
        :interests => []
      )

      if @user.present?
        user_params_hash.delete(:photo) unless user_params_hash[:photo].present?
      end


      user_params_hash[:birthdate] = DateTime.strptime(user_params_hash["birthdate"], "%m/%d/%Y %H:%M %p")
      user_params_hash[:interests] = user_params_hash[:interests].select { |interest| interest.present? }.join(',')

      user_params_hash
    end
end

app/helpers/user/events/current_helper.rb
module User::Events::CurrentHelper
end

app/helpers/user/private_messages_helper.rb
module User::PrivateMessagesHelper
end

app/helpers/user/profile_helper.rb
module User::ProfileHelper
end

app/helpers/user/voting_helper.rb
module User::VotingHelper
  def vote_status(voter, votable)
    vote = voter.voted_as_when_voted_for(votable)
    case vote
    when true
      "Favorite"
    when nil
      "No Preference"
    when false
      "Blocked"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def photo_url_for(user, dimensions, filename)
    return "" unless user.photo.present?
    "#{user.photo}-/scale_crop/#{dimensions}/center/#{filename}"
  end

  def profile_photo_url_for(user)
    photo_url_for(user, '350x350', 'profile.jpg')
  end

  def thumb_photo_url_for(user)
    photo_url_for(user, '150x150', 'thumb.jpg')
  end
end

app/views/user/private_messages/_form.html.erb
<%= form_with(model: user_private_message, local: true, :html => { :class => "event" }) do |f| %>
  <%= f.hidden_field :sender_id %>
  <%= f.hidden_field :recipient_id %>
  <%= f.hidden_field :event_id %>
  <% if user_private_message.errors.any? %>

    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(user_private_message.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% user_private_message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content, :class => 'control-label' %>
    <div>
      <%= f.text_area :content, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <% if user_private_message.message_intent_required? %>
    <div class="form-group">
      <%= f.label :message_intent, :class => 'control-label' %>

      <div>
        <% User::PrivateMessage::MESSAGE_INTENTS.each do |message_intent| %>
          <div class='form-check-inline'>
            <% checked = user_private_message.to_s.split(',').include?(message_intent) %>
            <%= f.check_box :message_intent, {multiple: true, checked: checked, class: "form-check-input"}, message_intent, "" %>
            <%= f.label message_intent, class: "form-check-label", for: "user_interests_#{message_intent.downcase}" %>
          </div>
        <% end %>
      </div>

    </div>
  <% end %>


  <div class="form-group">
    <%= f.submit "Send", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/user/private_messages/edit.html.erb
<h1>Editing User Private Message</h1>

<%= render 'form', user_private_message: @user_private_message %>

<%= link_to 'Show', @user_private_message %> |
<%= link_to 'Back', user_private_messages_path %>

app/views/user/private_messages/index.html.erb
<h2><%= @sender.name %> Messages</h2>
<%- model_class = User::PrivateMessage -%>

<% @user_private_messages.first.message_intent.split(',').each do |message_intent| %>
  <span class="badge badge-primary"><%= message_intent %></span>
<% end %>

  <% old_event_name = nil %>
  <% old_date = nil %>

    <table class="table table-striped">
    <% @user_private_messages.reorder(created_at: :desc).each do |user_private_message| %>
        <% new_event_name = user_private_message.event.name %>
        <% new_date = datetime_zoned_date(user_private_message.created_at, user_private_message.event.place) %>
        <% time = datetime_zoned_time(user_private_message.created_at, user_private_message.event.place) %>
        <% if old_event_name != new_event_name || old_date != new_date %>
          <% if old_date != nil %>
            </tbody>
          <% end %>
            <thead>
              <th colspan=4><%= new_date %> <%= user_private_message.event.name %></th>
            </thead>
            <tbody>
        <% end %>
          <tr>
            <td><%= time %></td>
            <td><%= user_private_message.sender.name %></td>
            <td>
              <% if user_private_message.is_unread_by?(current_user) %>
                <span class="badge badge-primary">New</span>
              <% end %>
              <%= user_private_message.content %>
            </td>
            <td>
              <% if user_private_message.sender_id == @sender.id %>
                <%= form_with url: user_current_message_modal_path(id: user_private_message.event.id) do |f| %>
                  <%= f.hidden_field :send_to_id, value: @sender.id %>
                  <div class="form-group">
                    <%= f.submit "Reply", :class => 'btn btn-primary btn-round' %>
                  </div>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% old_event_name = new_event_name %>
        <% old_date = new_date %>
    <% end %>
  </tbody>
</table>

<% if @event.present? %>
  <%= link_to "Event Threads", inbox_user_current_event_path(id: @event.id), class: 'btn btn-primary btn-round' %>


  <%= link_to "All Messages with #{@sender.name}",
              user_private_messages_path(sender_id: @sender.id, event_id: @current_event&.id),
              class: "btn btn-primary btn-round" %>
<% end %>
<%= link_to "All Threads", user_profile_messages_path, class: 'btn btn-primary btn-round' %>

app/views/user/private_messages/modal.js.erb
var eventsModal = $('#modal');

if (eventsModal.length > 0) {
  eventsModal.html("<%= j render(partial: 'user/events/modal') %>");
} else {
  console.log('#modal not found');
}
eventsModal.modal({
  show: true
});

app/views/user/private_messages/new.html.erb
<h1>New User Private Message</h1>

<%= render 'form', user_private_message: @user_private_message %>

<%= link_to 'Back', user_private_messages_path %>

app/views/user/private_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @user_private_message.content %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @user_private_message.sender %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @user_private_message.recipient %>
</p>

<%= link_to 'Edit', edit_user_private_message_path(@user_private_message) %> |
<%= link_to 'Back', user_private_messages_path %>